#!/usr/bin/python3
# character magnifier

import flet as ft


def main(page: ft.Page):
    page.title = "character magnifier"
    tf: ft.TextField = ft.TextField(label="target text")
    input: str = "読書鏡"
    tabs: list[ft.Tab] = []
    for s in input:
        tabs.append(
            ft.Tab(
                text=s,
                content=ft.Container(
                    content=ft.Text(s, size=288), alignment=ft.alignment.center
                )
            )
        )
    t = ft.Tabs(
        selected_index=0,
        animation_duration=300,
        tabs=tabs,
        expand=1,
    )
    page.add(tf, t)

ft.app(main)
